baseURL = "https://csyakamoz.github.io"
languageCode = "zh-cn"
title = "CsYakamoz`s Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"


[author]
  name = "CsYakamoz"

[languages]
  [languages.cn]
    contentDir = "content/"
    languageName = "Chinese"
    weight = 1

[params]
mainSections = ["post", "tags"]

[[params.socials]]
name = "Github"
link = "https://github.com/CsYakamoz"
[[params.socials]]
name = "LeetCode"
link = "https://leetcode.com/CsYakamoz/"
